### ISSUE TITLE
Kya hai ye???

### ISSUE THREAD

**Issue by nitinstp23** [rakesh87/journey#1]
Faltuuuuuuuuuu. :-1:

**Comment by rakesh87** [comment]
keep patience dude! :)
you will find some interesting content here.

On Wed, Apr 15, 2015 at 3:27 PM, Nitin Misra notifications@github.com
wrote:

> Faltuuuuuuuuuu. [image: :-1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rakesh87/journey/issues/1.

## 

Rakesh Verma
+91 725 927 8435

**Comment by nitinstp23** [comment]
:+1:
